### PR TITLE
Try to fix Torec issues by add login

### PR DESCRIPTION
**Pull request by myakove**
@gklein please try to verify it. thanks

### CODE REVIEW

**Comment by JonathancalderonIL** [comment]
Do problems solved on 1.0.8

**Comment by JonathancalderonIL** [comment]
DL

**Comment by myakove** [comment]
Verified, can someone else verify it too?
I have one problem the username and password have no title in the addon setting and I don't know how to set title for that (never wrote addon for kodi)

**Comment by gklein** [comment]
@myakove Great work! it seems to be working perfectly if I set the new user/password settings.

Let's check if there is an easy way to fix the display of the settings fields.

**Comment by gklein** [comment]
@myakove Can be fixed by adding a language file similar to:
https://github.com/XBMCil/service.subtitles.subtitle/blob/master/resources/language/English/strings.po

**Comment by myakove** [comment]
@gklein thanks. works. try now

**Comment by myakove** [comment]
@slmosl can you squash all my commits to one please

**Comment by itzikg** [comment]
@myakove 
It still does not work well ...
Banshee Season 4 Episode 6
http://i.imgur.com/jfK0xnd.jpg

**Comment by myakove** [comment]
@itzikg you are right it stops working again :(
@gklein do we have any more ideas?

**Comment by gklein** [comment]
@myakove @itzikg there is a new "userAuth" field added yesterday...

**Comment by myakove** [comment]
@gklein I saw it and it works if I send me userAuth but I have no idea how to get it

**Comment by CaTzil** [comment]
It looks like the owner add hard-coded value to 
http://www.torec.net/gjs/jquery1.3.2.min.js,jquery.all.min.js,user_functions.js,jquery.querystring.js,jquery.starrating.js,subw.js
var sub_Id,userAuth='EqPDsJVBAl6B3hyc';

**Comment by myakove** [comment]
@gklein thx, can you try now?

**Comment by CaTzil** [comment]
I think that reading that file is redundant, can you confirm that the userAuth at your file is with the same value (**EqPDsJVBAl6B3hyc**)?

**Comment by myakove** [comment]
I have the same value but @gklein had different one before

**Comment by avigdork** [comment]
I have the same value too. 
You can add a call to this file and get the userAuth value when needed.

**Comment by CaTzil** [comment]
Cause it is a static file, Torec owner will have to make it static, so you can attach that variable hard-coded in the plugin.

**Comment by avigdork** [comment]
But if they change the hard coded value, you don't need to change the addon code if you get it from the file.

**Comment by gklein** [comment]
@CaTzil  Yes, it is a static value but was changed from what it was yesterday, so I guess @myakove  implementation make sense after all.

@myakove  Looks good, and seems to working well on a few movies I've tried!  10x

**Comment by itzikg** [comment]
@myakove 
 thanks it works.

**Comment by CaTzil** [comment]
@myakove,
You can make the request smaller by addressing http://www.torec.net/gjs/subw.js

**Comment by myakove** [comment]
@CaTzil thx

**Comment by myakove** [comment]
update with @CaTzil link

**Comment by ogolan** [comment]
I'm trying to install but get error message that I'm missing dependencies.  What I should do?

**Comment by myakove** [comment]
I didn't add any now modules, please attach log

**Comment by ogolan** [comment]
attached
[log.zip](https://github.com/XBMCil/service.subtitles.torec/files/262755/log.zip)

**Comment by myakove** [comment]
Can you try to update with debug on in setting?

**Comment by myakove** [comment]
And send the log with debug

**Comment by ogolan** [comment]
are you talking about the setting inside torec addon? if so, this is disabled together with the update option. I think it is on the the problems. or you are talking on debug in another location?

**Comment by myakove** [comment]
debug in kodi setting under setting>system>logging

**Comment by ogolan** [comment]
there you go:
[log.zip](https://github.com/XBMCil/service.subtitles.torec/files/262823/log.zip)

**Comment by myakove** [comment]
which version of kodi you have?

**Comment by ogolan** [comment]
15.2

**Comment by myakove** [comment]
ok, so kodi 15.2, And I don't see debug logs while the update fail.
Anyone can tell if the plugin is support for kodi 15.2 or can look at the log?
Maybe try to upgrade to 16?

**Comment by ogolan** [comment]
one thing I noticed in the log:
11:33:58 T:9780   DEBUG: CAddonInstallJob[script.common.plugin.cache]: requires xbmc.python version 2.24.0 which is not available
11:33:58 T:9780   ERROR: CAddonInstallJob[service.subtitles.torec]: dependency check failed

so it looks like python version of kodi. maybe 16 would help. I can try that and let you know

**Comment by ogolan** [comment]
yes, updating to 16.1 worked! 
Thanks a lot!

**Comment by itzikg** [comment]
@myakove 
The torec site has blocked addon again
http://pastebin.com/6Gc6TTcy

**Comment by slmosl** [comment]
great job @myakove, I'll merge this branch and make the necssary changes to make the addon work again very soon

**Pull request merged**
